package com.etiqa.specification;

public enum SearchCriteria {
    GREATER_THAN, LESS_THAN, GREATER_THAN_EQUAL, LESS_THAN_EQUAL, NOT_EQUAL, EQUAL, EQUAL_IGNORE_CASE, MATCH,
    MATCH_START, MATCH_END, IN, NOT_IN
}
